- name: Download AWS CLI v2
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'

- name: Unzip AWS CLI
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes
    creates: /tmp/aws

- name: Install AWS CLI
  command: ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
  args:
    chdir: /tmp
    creates: /usr/local/bin/aws

- name: Verify AWS CLI installation
  command: aws --version
  register: aws_cli_version
  changed_when: false