- name: Install curl
  yum:
    name: curl
    state: present

- name: Install ca-certificates
  yum:
    name: ca-certificates
    state: present

- name: Install gnupg
  yum:
    name: gnupg
    state: present

- name: Add Jenkins repository (Amazon Linux)
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/jenkins.repo
    content: |
      [jenkins]
      name=Jenkins
      baseurl=https://pkg.jenkins.io/redhat-stable/
      gpgcheck=1
      gpgkey=https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      enabled=1

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Enable and start Jenkins service
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: yes
