apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: auth-service
spec:
  replicas: {{ .Values.authService.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets: 
        {{- toYaml .Values.imagePullSecrets | nindent 8  }}
      containers:
        - name: auth-container
          image: {{ .Values.authService.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.authService.containerPort }}
          env:
            - name: DB_HOST
              value: {{ .Values.authService.db.host }}
            - name: DB_PORT
              value: {{ .Values.authService.db.port | quote }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: password
            - name: DB_SSL_MODE
              value: {{ .Values.authService.db.sslMode }}
            - name: DB_SSL_CA_FILE_PATH
              value: {{ .Values.authService.db.caFilePath }}
          volumeMounts:
            - name: ca-cert-volume
              mountPath: /etc/ssl/certs/rds
              readOnly: true
      volumes:
        - name: ca-cert-volume
          configMap:
            name: rds-ca
            items:
              - key: rds-combined-ca-bundle.pem
                path: rds-combined-ca-bundle.pem
