apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: {{ include "todo-app.namespace" . }}
spec:
  selector:
    app: todo-service
  ports:
    - protocol: TCP
      port: {{ .Values.todoService.service.port }}
      targetPort: {{ .Values.todoService.service.targetPort }}