- name: Install Amazon Corretto 17 using yum
  ansible.builtin.yum:
    name: java-17-amazon-corretto
    state: present
    use_backend: yum




- name: Set Java alternatives automatically
  ansible.builtin.shell: |
    alternatives --install /usr/bin/java java /opt/amazon-corretto-17/bin/java 2000
    alternatives --set java /opt/amazon-corretto-17/bin/java
