apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: todo-app
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 328986589640.dkr.ecr.eu-central-1.amazonaws.com/todo-app-frontend:latest
          ports:
          - containerPort: 80
          env:
            - name: API_BASE_URL
              value: "/api"