apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
  namespace: {{ include "todo-app.namespace" . }}
  labels:
    app: api-service
spec:
  replicas: {{ .Values.apiService.replicaCount }}
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-container
          image: "{{ .Values.global.image.repository }}/{{ .Values.apiService.image.name }}:{{ .Values.global.image.tag }}"
          ports:
            - containerPort: {{ .Values.apiService.service.port }}
          env:
            - name: AUTH_SERVICE_URL
              value: {{ .Values.apiService.env.AUTH_SERVICE_URL }}
            - name: TODO_SERVICE_URL
              value: {{ .Values.apiService.env.TODO_SERVICE_URL }}
