apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: {{ include "todo-app.namespace" . }}
  labels:
    app: api-service
spec:
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: {{ .Values.apiService.service.port }}
      targetPort: {{ .Values.apiService.service.port }}
