apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::328986589640:role/depi-eks-cluster-eks-node-group-role
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - userarn: arn:aws:iam::328986589640:user/gimmeursocks
      username: gimmeursocks
      groups:
        - system:masters
    - userarn: arn:aws:iam::328986589640:user/hafez
      username: hafez
      groups:
        - system:masters

kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-09T12:54:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2271"
  uid: a5c9fb31-a177-4b14-aa8b-5c2874b49271
