{{- range $svc := list .Values.apiService .Values.frontend }}
{{- if $svc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc.name }}-deployment
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $svc.name }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: {{ $svc.name }}
  template:
    metadata:
      labels:
        app: {{ $svc.name }}
    spec:
      imagePullSecrets:
        {{- toYaml $.Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ $svc.name }}-container
          image: {{ $svc.image }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $svc.containerPort }}
          env:
            {{- if $svc.env }}
            {{- toYaml $svc.env | nindent 12 }}
            {{- end }}
{{- end }}
---
{{- end }}
