{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
data:
  db_name: {{ .db_name }}
  username: {{ .username }}
  password: {{ .password }}
---
{{- end }}
