apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ include "todo-app.namespace" . }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: "{{ .Values.global.image.repository }}/{{ .Values.frontend.image.name }}:{{ .Values.global.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          env:
            - name: API_BASE_URL
              value: {{ .Values.frontend.env.API_BASE_URL }}