apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-service
spec:
  replicas: {{ .Values.todoService.replicaCount }}
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      imagePullSecrets: 
        {{- toYaml .Values.imagePullSecrets | nindent 8  }}
      containers:
        - name: todo-container
          image: {{ .Values.todoService.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.todoService.containerPort }}
          env:
            - name: DB_HOST
              value: {{ .Values.todoService.db.host }}
            - name: DB_PORT
              value: {{ .Values.todoService.db.port | quote }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: todo-database-secret
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: todo-database-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-database-secret
                  key: password
            - name: DB_TLS
              value: "true"
            - name: DB_CA_FILE_PATH
              value: {{ .Values.todoService.db.caFilePath }}
          volumeMounts:
            - name: ca-cert-volume
              mountPath: /etc/ssl/certs/documentdb
              readOnly: true
      volumes:
        - name: ca-cert-volume
          configMap:
            name: documentdb-ca
            items:
              - key: global-bundle.pem
                path: global-bundle.pem