apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-service
spec:
  selector:
    app: todo-service
  ports:
    - protocol: TCP
      port: {{ .Values.todoService.servicePort }}
      targetPort: {{ .Values.todoService.containerPort }}