apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: todo-app
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3005