apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: todo-app
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-container
          image: 328986589640.dkr.ecr.eu-central-1.amazonaws.com/todo-app-auth-service:latest
          ports:
            - containerPort: 3005
          env:
            - name: DB_HOST
              value: authdb.c5s0m42mw1t1.eu-central-1.rds.amazonaws.com
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: password
            - name: DB_SSL_MODE
              value: "verify-ca"
            - name: DB_SSL_CA_FILE_PATH
              value: /etc/ssl/certs/rds/rds-combined-ca-bundle.pem
          volumeMounts:
            - name: ca-cert-volume
              mountPath: /etc/ssl/certs/rds
              readOnly: true
      volumes:
        - name: ca-cert-volume
          configMap:
            name: rds-ca
            items:
              - key: rds-combined-ca-bundle.pem
                path: rds-combined-ca-bundle.pem