apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
  namespace: todo-app
  labels:
    app: api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-container
          image: 328986589640.dkr.ecr.eu-central-1.amazonaws.com/todo-app-api-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_SERVICE_URL
              value: auth-service:3000
            - name: TODO_SERVICE_URL
              value: todo-service:3000
