apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: todo-app
  labels:
    app: api-service
spec:
  type: LoadBalancer
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
