apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-app
  labels:
    app: todo-service
spec:
  selector:
    app: todo-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3006