apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: todo-database-secret
  namespace: {{ .Values.namespace }}
data:
  db_name: {{ .Values.todoSecret.db_name }}
  username: {{ .Values.todoSecret.username }}
  password: {{ .Values.todoSecret.password }}
