---
- name: Enable Docker topic from amazon-linux-extras
  ansible.builtin.shell: amazon-linux-extras enable docker

- name: Install Docker (after enabling via extras)
  ansible.builtin.shell: yum install -y docker

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started

- name: Add jenkins user to docker group
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes
