- hosts: mycontainers
  become: yes
  tasks:
    # === Install Java (required by Jenkins) ===
    - name: Install Java using Amazon correto
      ansible.builtin.package:
        name: java-17-amazon-corretto-devel
        state: present

    - name: Install curl, gnupg, and other dependencies
      ansible.builtin.package:
        name:
          - curl
          - ca-certificates
          - gnupg
        state: present

    # === Install Jenkins ===
    - name: Add Jenkins repository (Amazon Linux)
      ansible.builtin.yum_repository:
        name: jenkins
        description: Jenkins repo
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        enabled: yes

    - name: Install Jenkins
      ansible.builtin.package:
        name: jenkins
        state: present

    - name: Enable and start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes

    # === Docker Installation ===
    - name: Enable Docker topic from amazon-linux-extras
      community.general.amazon_linux_extras:
        name: docker
        state: present

    - name: Install Docker (after enabling via extras)
      ansible.builtin.package:
        name: docker
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started
    
    - name: Add jenkins user to docker group
      ansible.builtin.user:
        name: jenkins
        groups: docker
        append: yes

    # === Install kubectl ===
    - name: Download kubectl
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v1.26.3/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Verify kubectl version
      ansible.builtin.command: kubectl version --client
      register: kubectl_version
      changed_when: false
      failed_when: kubectl_version.rc != 0
