- hosts: mycontainers
  become: yes
  tasks:
    # === Install Java (required by Jenkins) ===
    - name: Install Java (Amazon Linux)
      ansible.builtin.package:
        name: java-17-openjdk
        state: present

    - name: Install curl, gnupg, and other dependencies
      ansible.builtin.package:
        name:
          - curl
          - gnupg
          - ca-certificates
          - lsb-release
        state: present

    # === Install Jenkins ===
    - name: Add Jenkins repository (Amazon Linux)
      ansible.builtin.yum_repository:
        name: jenkins
        description: Jenkins repo
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        enabled: yes

    - name: Install Jenkins
      ansible.builtin.package:
        name: jenkins
        state: present

    # === Docker Installation ===
    - name: Add Docker yum repository (Amazon Linux)
      ansible.builtin.yum_repository:
        name: docker
        description: Docker CE Stable - x86_64
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install Docker Engine
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    # === Install kubectl ===
    - name: Download kubectl from Kubernetes official site
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v1.26.3/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Verify kubectl version
      ansible.builtin.command: kubectl version --client
      register: kubectl_version
      failed_when: kubectl_version.rc != 0
      changed_when: false
