- hosts: jenkins_master
  become: yes
  vars:
    ansible_pkg_mgr: yum
    private_ip: "{{ jenkins_private_ip }}" 
  roles:
    - java
    - maven
    - jenkins
    - docker
    - kubectl
    - aws_cli
    - git
    - jenkins_admin
    - jenkins_agent