apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ include "todo-app.namespace" . }}
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: {{ .Values.authService.service.port }}
      targetPort: {{ .Values.authService.service.targetPort }}