name: Terraform CI/CD

on:
  push:
    branches:
      - main 

jobs:
  terraform:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  

      - name: Install Ansible ansible<10
        run: |
          python -m pip install --upgrade pip
          pip install 'ansible<10'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: eu-central-1 

      - name: Terraform Init
        run: terraform init 
        working-directory: terraform
        
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform
        
      - name: Terraform Apply
        run: terraform apply -auto-approve 
        working-directory: terraform

      - name: Capture Terraform Outputs
        id: tf_outputs
        run: |
          echo "JENKINS_MASTER_DNS=$(terraform -chdir=terraform output -raw jenkins_master_public_dns)" >> $GITHUB_ENV
          echo "JENKINS_MASTER_PRIVATE_IP=$(terraform -chdir=terraform output -raw jenkins_master_private_ip)" >> $GITHUB_ENV

      - name: Write SSH Private Key
        run: |
          echo "${{ secrets.JENKINS_SERVER_SSH_KEY }}" > private-key.pem
          chmod 600 private-key.pem

      - name: Generate Ansible Inventory for Jenkins Master
        run: |
          cd ansible
          echo "[jenkins_master]" > inventory.ini
          echo "ec2-user@${{ env.JENKINS_MASTER_DNS }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory.ini
          echo "" >> inventory.ini
          echo "[defaults]" >> inventory.ini
          echo "ansible_python_interpreter=/usr/local/bin/python3.8" >> inventory.ini


      - name: Run Ansible Playbook - Jenkins Master
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/jenkins_master.yml \
          --private-key ./private-key.pem

      - name: Get Jenkins Master Private IP
        id: get_ip
        run: |
          jenkins_master_ip=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=jenkins-master" --query "Reservations[0].Instances[0].PrivateIpAddress" --output text)
          echo "jenkins_master_private_ip=$jenkins_master_ip" >> $GITHUB_ENV

      - name: Get Jenkins Secret from AWS Secrets Manager
        id: get_jenkins_secret
        run: |
          jenkins_secret=$(aws secretsmanager get-secret-value --secret-id JenkinsSecret --query SecretString --output text)
          echo "jenkins_secret=$jenkins_secret" >> $GITHUB_ENV

      - name: Add Jenkins agent to inventory
        run: |
          echo "[jenkins_agents]" >> inventory
          echo "ec2-user@${{ env.jenkins_master_private_ip }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory
          echo "[jenkins_agents:vars]" >> inventory
          echo "jenkins_master_private_ip=${{ env.jenkins_master_private_ip }}" >> inventory
          echo "jenkins_secret=${{ env.jenkins_secret }}" >> inventory

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/jenkins_agent.yml \
          --private-key ./private-key.pem