name: Terraform CI/CD

on:
  push:
    branches:
      - main 

jobs:
  terraform:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  

      - name: Install Ansible ansible<10
        run: |
          python -m pip install --upgrade pip
          pip install 'ansible<10'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: eu-central-1 

      - name: Terraform Init
        run: terraform init 
        working-directory: terraform
       
      - name: Terraform Apply
        run: terraform apply -auto-approve 
        working-directory: terraform
        continue-on-error: true
        
      - name: Terraform Import
        run: terraform import module.eks.kubernetes_config_map.aws_auth kube-system/aws-auth
        working-directory: terraform
        continue-on-error: true

      - name: Terraform Apply after import
        run: terraform apply -auto-approve 
        working-directory: terraform
      - name: Capture Terraform Outputs
        id: tf_outputs
        run: |
          echo "JENKINS_MASTER_DNS=$(terraform -chdir=terraform output -raw jenkins_master_public_dns)" >> $GITHUB_ENV
          echo "JENKINS_AGENT_DNS=$(terraform -chdir=terraform output -raw jenkins_agent_public_dns)" >> $GITHUB_ENV
          echo "JENKINS_MASTER_PRIVATE_IP=$(terraform -chdir=terraform output -raw jenkins_master_private_ip)" >> $GITHUB_ENV

      - name: Write SSH Private Key
        run: |
          echo "${{ secrets.JENKINS_SERVER_SSH_KEY }}" > private-key.pem
          chmod 600 private-key.pem

      - name: Generate Ansible Inventory for Jenkins Master
        run: |
          cd ansible
          echo "[jenkins_master]" > inventory.ini
          echo "ec2-user@${{ env.JENKINS_MASTER_DNS }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory.ini
          echo "" >> inventory.ini
          echo "[jenkins_master:vars]" >> inventory.ini
          echo "jenkins_private_ip=${{ env.JENKINS_MASTER_PRIVATE_IP }}" >> inventory.ini
          echo "" >> inventory.ini
          echo "[defaults]" >> inventory.ini
          echo "ansible_python_interpreter=/usr/local/bin/python3.8" >> inventory.ini


      - name: Run Ansible Playbook - Jenkins Master
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/jenkins_master.yml \
          --private-key ./private-key.pem

      - name: Capture Jenkins Agent JNLP Secret
        run: |
          export AGENT_JNLP_SECRET=$(cat /var/lib/jenkins/agent-jnlp-secret.txt)
          echo "JNLP_SECRET=${AGENT_JNLP_SECRET}" >> $GITHUB_ENV
        
      - name: Generate Ansible Inventory for Jenkins Agent
        run: |
          cd ansible
          echo "[jenkins_agent]" > inventory2.ini
          echo "ec2-user@${{ env.JENKINS_AGENT_DNS }} ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory2.ini
          echo "" >> inventory2.ini
          echo "[jenkins_agent:vars]" >> inventory2.ini
          echo "jenkins_master_private_ip=${{ env.JENKINS_AGENT_DNS }}" >> inventory2.ini
          echo "jenkins_secret=${{ env.AGENT_JNLP_SECRET }}" >> inventory2.ini
          echo "" >> inventory2.ini
          echo "[defaults]" >> inventory2.ini
          echo "ansible_python_interpreter=/usr/local/bin/python3.8" >> inventory2.ini

  
      - name: Run Ansible Playbook - Jenkins Agent
        run: |
          ansible-playbook -i ansible/inventory2.ini ansible/jenkins_agent.yml \
          --private-key ./private-key.pem
    